import { db } from '@/lib/db';
import { NextResponse } from 'next/server';

// POST /api/focus-groups/seed — Seed 10 dummy focus group listings
export async function POST() {
  try {
    // Delete existing focus group seed data
    await db.focusGroupApplication.deleteMany({});
    const existingListings = await db.focusGroupListing.findMany({ select: { id: true } });
    if (existingListings.length > 0) {
      await db.focusGroupListing.deleteMany({});
    }

    // ─── Create or reuse dummy company/creator users ───────────────────
    const companyUsers = [
      { username: 'nielsenresearch', displayName: 'Nielsen Research Group' },
      { username: 'mckinsey_insights', displayName: 'McKinsey & Co' },
      { username: 'pg_consumer', displayName: 'P&G Consumer Insights' },
      { username: 'googleux_lab', displayName: 'Google UX Lab' },
      { username: 'stanford_research', displayName: 'Stanford Research Group' },
      { username: 'ford_motorlabs', displayName: 'Ford Motor Innovation Lab' },
      { username: 'mayo_health', displayName: 'Mayo Clinic Research' },
      { username: 'goldman_sachssurvey', displayName: 'Goldman Sachs Research' },
      { username: 'spotify_insights', displayName: 'Spotify Insights Team' },
      { username: 'tesla_research', displayName: 'Tesla Research Division' },
    ];

    const createdUsers: { id: string; username: string; displayName: string }[] = [];
    for (const u of companyUsers) {
      const existing = await db.user.findUnique({ where: { username: u.username } });
      if (existing) {
        createdUsers.push({ id: existing.id, username: existing.username, displayName: existing.displayName ?? u.displayName });
      } else {
        const user = await db.user.create({
          data: {
            username: u.username,
            email: `${u.username}@seed.fmf`,
            passwordHash: '$2b$10$seed_hash_not_real_password',
            displayName: u.displayName,
            role: 'creator',
            memberScore: 950,
            isVerified: true,
            onboardingCompleted: true,
          },
        });
        createdUsers.push({ id: user.id, username: user.username, displayName: user.displayName ?? u.displayName });
      }
    }

    // ─── Create 10 diverse dummy focus group listings ──────────────────
    const now = Date.now();
    const day = 86400000;

    const listings = [
      {
        creatorId: createdUsers[0].id,
        creatorUsername: createdUsers[0].username,
        creatorDisplayName: createdUsers[0].displayName,
        title: 'Consumer Shopping Habits in the Age of AI',
        description: 'We are conducting a 90-minute live focus group to understand how AI-driven recommendations are changing the way consumers discover and purchase products. Participants will discuss their shopping journeys, share screen recordings, and provide feedback on prototype recommendation engines.',
        companyName: 'Nielsen Research',
        industry: 'Consumer Goods',
        sessionFormat: 'live',
        sessionDuration: 90,
        scheduledAt: new Date(now + 5 * day),
        rewardPerParticipant: 75.00,
        totalSlots: 12,
        filledSlots: 8,
        totalBudget: 900,
        minScore: 300,
        verifiedOnly: true,
        minPollResponses: 10,
        location: 'United States',
        ageRange: '25-45',
        gender: null,
        interests: '["consumer goods","AI","shopping","e-commerce"]',
        status: 'open',
        closesAt: new Date(now + 4 * day),
        applicationsCount: 23,
      },
      {
        creatorId: createdUsers[1].id,
        creatorUsername: createdUsers[1].username,
        creatorDisplayName: createdUsers[1].displayName,
        title: 'Future of Remote Work — Executive Perspectives',
        description: 'An exclusive async video focus group for senior professionals and managers. Share your insights on hybrid work policies, productivity tools, and team collaboration challenges. Record a 15-minute video response at your convenience within the next 2 weeks.',
        companyName: 'McKinsey & Co',
        industry: 'Finance',
        sessionFormat: 'async_video',
        sessionDuration: 15,
        rewardPerParticipant: 50.00,
        totalSlots: 20,
        filledSlots: 11,
        totalBudget: 1000,
        minScore: 500,
        verifiedOnly: true,
        minPollResponses: 5,
        location: null,
        ageRange: '30-55',
        gender: null,
        interests: '["business","remote work","management","productivity"]',
        status: 'open',
        closesAt: new Date(now + 14 * day),
        applicationsCount: 45,
      },
      {
        creatorId: createdUsers[2].id,
        creatorUsername: createdUsers[2].username,
        creatorDisplayName: createdUsers[2].displayName,
        title: 'Men\'s Grooming Product Preferences — Gen Z',
        description: 'Help P&G shape the next generation of men\'s grooming products. We want to hear from Gen Z males about their skincare routines, brand preferences, and purchase decisions. This hybrid session includes a brief live discussion followed by a take-home product trial with async feedback.',
        companyName: 'P&G Consumer Insights',
        industry: 'Consumer Goods',
        sessionFormat: 'hybrid',
        sessionDuration: 45,
        scheduledAt: new Date(now + 7 * day),
        rewardPerParticipant: 40.00,
        totalSlots: 15,
        filledSlots: 6,
        totalBudget: 600,
        minScore: 150,
        verifiedOnly: false,
        minPollResponses: 3,
        location: 'United States',
        ageRange: '18-27',
        gender: 'male',
        interests: '["grooming","skincare","consumer goods","Gen Z"]',
        status: 'open',
        closesAt: new Date(now + 6 * day),
        applicationsCount: 34,
      },
      {
        creatorId: createdUsers[3].id,
        creatorUsername: createdUsers[3].username,
        creatorDisplayName: createdUsers[3].displayName,
        title: 'Google Maps UX Redesign — Navigation Feedback',
        description: 'We are redesigning the Google Maps navigation experience and need your feedback. Participate in a 60-minute moderated UX session where you will test new navigation prototypes and share your thoughts on usability, clarity, and feature prioritization.',
        companyName: 'Google UX Lab',
        industry: 'Tech',
        sessionFormat: 'live',
        sessionDuration: 60,
        scheduledAt: new Date(now + 3 * day),
        rewardPerParticipant: 60.00,
        totalSlots: 8,
        filledSlots: 5,
        totalBudget: 480,
        minScore: 400,
        verifiedOnly: true,
        minPollResponses: 10,
        location: null,
        ageRange: '21-50',
        gender: null,
        interests: '["technology","UX","navigation","mobile apps"]',
        status: 'open',
        closesAt: new Date(now + 2 * day),
        applicationsCount: 56,
      },
      {
        creatorId: createdUsers[4].id,
        creatorUsername: createdUsers[4].username,
        creatorDisplayName: createdUsers[4].displayName,
        title: 'Online Education Effectiveness — Educator Roundtable',
        description: 'Stanford Research Group is hosting a text-based async focus group for educators to discuss the effectiveness of online learning platforms. Share your experiences teaching remotely, challenges with student engagement, and recommendations for improvement. Contribute over 5 days at your own pace.',
        companyName: 'Stanford Research Group',
        industry: 'Education',
        sessionFormat: 'async_text',
        sessionDuration: 30,
        rewardPerParticipant: 25.00,
        totalSlots: 25,
        filledSlots: 18,
        totalBudget: 625,
        minScore: 200,
        verifiedOnly: false,
        minPollResponses: 5,
        location: null,
        ageRange: null,
        gender: null,
        interests: '["education","online learning","teaching","e-learning"]',
        status: 'open',
        closesAt: new Date(now + 10 * day),
        applicationsCount: 42,
      },
      {
        creatorId: createdUsers[5].id,
        creatorUsername: createdUsers[5].username,
        creatorDisplayName: createdUsers[5].displayName,
        title: 'Electric Vehicle Charging Experience — Current Owners',
        description: 'Ford is gathering EV owners for a live focus group to discuss real-world charging experiences. Topics include home vs. public charging, range anxiety, charging network reliability, and willingness to pay for premium charging features. Must own or lease an EV.',
        companyName: 'Ford Motor Innovation Lab',
        industry: 'Automotive',
        sessionFormat: 'live',
        sessionDuration: 75,
        scheduledAt: new Date(now + 10 * day),
        rewardPerParticipant: 65.00,
        totalSlots: 10,
        filledSlots: 3,
        totalBudget: 650,
        minScore: 250,
        verifiedOnly: false,
        minPollResponses: 3,
        location: 'United States',
        ageRange: '25-60',
        gender: null,
        interests: '["electric vehicles","automotive","charging","sustainability"]',
        status: 'open',
        closesAt: new Date(now + 9 * day),
        applicationsCount: 19,
      },
      {
        creatorId: createdUsers[6].id,
        creatorUsername: createdUsers[6].username,
        creatorDisplayName: createdUsers[6].displayName,
        title: 'Patient Experience with Telehealth Services',
        description: 'Help us improve telehealth experiences for patients worldwide. This async video focus group asks you to share your experiences with virtual doctor visits, prescription management apps, and remote health monitoring. Your feedback will directly influence the next generation of digital health tools.',
        companyName: 'Mayo Clinic Research',
        industry: 'Healthcare',
        sessionFormat: 'async_video',
        sessionDuration: 20,
        rewardPerParticipant: 35.00,
        totalSlots: 30,
        filledSlots: 22,
        totalBudget: 1050,
        minScore: 100,
        verifiedOnly: false,
        minPollResponses: 2,
        location: null,
        ageRange: '18-70',
        gender: null,
        interests: '["healthcare","telehealth","digital health","patient experience"]',
        status: 'open',
        closesAt: new Date(now + 8 * day),
        applicationsCount: 67,
      },
      {
        creatorId: createdUsers[7].id,
        creatorUsername: createdUsers[7].username,
        creatorDisplayName: createdUsers[7].displayName,
        title: 'Retail Investor Sentiment — Market Outlook 2026',
        description: 'Goldman Sachs Research is conducting a live focus group with active retail investors to understand market sentiment, portfolio strategies, and risk appetite heading into 2026. Participants should have at least 2 years of active investing experience.',
        companyName: 'Goldman Sachs Research',
        industry: 'Finance',
        sessionFormat: 'live',
        sessionDuration: 60,
        scheduledAt: new Date(now + 4 * day),
        rewardPerParticipant: 70.00,
        totalSlots: 10,
        filledSlots: 7,
        totalBudget: 700,
        minScore: 600,
        verifiedOnly: true,
        minPollResponses: 15,
        location: null,
        ageRange: '25-60',
        gender: null,
        interests: '["finance","investing","stock market","economics"]',
        status: 'open',
        closesAt: new Date(now + 3 * day),
        applicationsCount: 38,
      },
      {
        creatorId: createdUsers[8].id,
        creatorUsername: createdUsers[8].username,
        creatorDisplayName: createdUsers[8].displayName,
        title: 'Podcast Discovery & Listening Habits',
        description: 'Spotify wants to understand how listeners discover new podcasts and what keeps them engaged. Share your thoughts in a 30-minute async video session covering discovery methods, subscription behavior, ad tolerance, and content preferences. Premium compensation for frequent podcast listeners.',
        companyName: 'Spotify Insights Team',
        industry: 'Tech',
        sessionFormat: 'async_video',
        sessionDuration: 30,
        rewardPerParticipant: 20.00,
        totalSlots: 40,
        filledSlots: 28,
        totalBudget: 800,
        minScore: 100,
        verifiedOnly: false,
        minPollResponses: 3,
        location: null,
        ageRange: '18-45',
        gender: null,
        interests: '["podcasts","music","audio","streaming","entertainment"]',
        status: 'open',
        closesAt: new Date(now + 12 * day),
        applicationsCount: 89,
      },
      {
        creatorId: createdUsers[9].id,
        creatorUsername: createdUsers[9].username,
        creatorDisplayName: createdUsers[9].displayName,
        title: 'Autonomous Vehicle Trust & Safety Perceptions',
        description: 'Tesla Research is conducting a hybrid focus group to explore public perceptions of autonomous driving technology. The session includes a live panel discussion followed by an async survey component about trust, safety concerns, and feature expectations for self-driving vehicles.',
        companyName: 'Tesla Research Division',
        industry: 'Automotive',
        sessionFormat: 'hybrid',
        sessionDuration: 60,
        scheduledAt: new Date(now + 14 * day),
        rewardPerParticipant: 55.00,
        totalSlots: 15,
        filledSlots: 2,
        totalBudget: 825,
        minScore: 200,
        verifiedOnly: false,
        minPollResponses: 5,
        location: null,
        ageRange: '21-60',
        gender: null,
        interests: '["autonomous vehicles","technology","safety","automotive","AI"]',
        status: 'open',
        closesAt: new Date(now + 13 * day),
        applicationsCount: 27,
      },
    ];

    const created = await db.focusGroupListing.createMany({
      data: listings.map((l) => ({
        ...l,
        updatedAt: new Date(),
      })),
    });

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${created.count} focus group listings.`,
      total: created.count,
    });
  } catch (error) {
    console.error('POST /api/focus-groups/seed error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to seed focus group data' },
      { status: 500 }
    );
  }
}
