import { db } from '@/lib/db';
import { NextResponse } from 'next/server';

// POST /api/survey-marketplace/seed — Seed 10 dummy survey listings
export async function POST() {
  try {
    // Delete existing survey seed data
    await db.surveyApplication.deleteMany({});
    const existingListings = await db.surveyListing.findMany({ select: { id: true } });
    if (existingListings.length > 0) {
      await db.surveyListing.deleteMany({});
    }

    // ─── Create or reuse dummy organization/creator users ──────────────
    const orgUsers = [
      { username: 'pew_research', displayName: 'Pew Research Center' },
      { username: 'forrester_research', displayName: 'Forrester Research' },
      { username: 'deloitte_digital', displayName: 'Deloitte Digital' },
      { username: 'who_survey', displayName: 'WHO Health Survey' },
      { username: 'hbs_research', displayName: 'Harvard Business School' },
      { username: 'gallup_polls', displayName: 'Gallup Polls' },
      { username: 'idc_analytics', displayName: 'IDC Analytics' },
      { username: 'nature_survey', displayName: 'Nature Research Survey' },
      { username: 'urban_institute', displayName: 'Urban Institute' },
      { username: 'consumer_reports_survey', displayName: 'Consumer Reports Survey' },
    ];

    const createdUsers: { id: string; username: string; displayName: string }[] = [];
    for (const u of orgUsers) {
      const existing = await db.user.findUnique({ where: { username: u.username } });
      if (existing) {
        createdUsers.push({ id: existing.id, username: existing.username, displayName: existing.displayName ?? u.displayName });
      } else {
        const user = await db.user.create({
          data: {
            username: u.username,
            email: `${u.username}@seed.fmf`,
            passwordHash: '$2b$10$seed_hash_not_real_password',
            displayName: u.displayName,
            role: 'creator',
            memberScore: 950,
            isVerified: true,
            onboardingCompleted: true,
          },
        });
        createdUsers.push({ id: user.id, username: user.username, displayName: user.displayName ?? u.displayName });
      }
    }

    // ─── Create 10 diverse dummy survey listings ───────────────────────
    const now = Date.now();
    const day = 86400000;

    const listings = [
      {
        creatorId: createdUsers[0].id,
        creatorUsername: createdUsers[0].username,
        creatorDisplayName: createdUsers[0].displayName,
        title: 'Social Media & Democracy — 2026 Midterm Election Awareness',
        description: 'Pew Research Center is conducting its annual survey on how Americans consume political information through social media. This 15-minute survey covers news source credibility, algorithm awareness, and political polarization. Your responses contribute to our widely-cited Digital Politics Report.',
        organizationName: 'Pew Research Center',
        sector: 'Political',
        surveyType: 'political',
        estimatedMinutes: 15,
        questionsCount: 25,
        rewardPerResponse: 5.00,
        totalSlots: 500,
        filledSlots: 387,
        totalBudget: 2500,
        minScore: 100,
        verifiedOnly: false,
        minPollResponses: 2,
        location: 'United States',
        ageRange: '18-70',
        gender: null,
        interests: '["politics","social media","democracy","news","voting"]',
        status: 'open',
        closesAt: new Date(now + 7 * day),
        applicationsCount: 412,
      },
      {
        creatorId: createdUsers[1].id,
        creatorUsername: createdUsers[1].username,
        creatorDisplayName: createdUsers[1].displayName,
        title: 'Enterprise SaaS Buying Behavior — IT Decision Makers',
        description: 'Forrester is surveying IT decision makers about their enterprise software purchasing process. Topics include evaluation criteria, vendor selection timelines, budget allocation, and satisfaction with current tools. This 20-minute survey is part of our Q2 2026 B2B Software Forecast.',
        organizationName: 'Forrester Research',
        sector: 'Technology',
        surveyType: 'market_research',
        estimatedMinutes: 20,
        questionsCount: 30,
        rewardPerResponse: 12.00,
        totalSlots: 200,
        filledSlots: 134,
        totalBudget: 2400,
        minScore: 400,
        verifiedOnly: true,
        minPollResponses: 8,
        location: null,
        ageRange: '28-55',
        gender: null,
        interests: '["enterprise software","SaaS","IT","B2B","technology"]',
        status: 'open',
        closesAt: new Date(now + 14 * day),
        applicationsCount: 178,
      },
      {
        creatorId: createdUsers[2].id,
        creatorUsername: createdUsers[2].username,
        creatorDisplayName: createdUsers[2].displayName,
        title: 'Digital Transformation Readiness — Retail Sector',
        description: 'Deloitte Digital is assessing retail companies\' readiness for AI-powered digital transformation. This 25-minute survey covers current technology infrastructure, data analytics capabilities, customer experience strategies, and barriers to adoption. Results inform our annual Retail Tech Maturity Index.',
        organizationName: 'Deloitte Digital',
        sector: 'Technology',
        surveyType: 'market_research',
        estimatedMinutes: 25,
        questionsCount: 35,
        rewardPerResponse: 15.00,
        totalSlots: 150,
        filledSlots: 89,
        totalBudget: 2250,
        minScore: 300,
        verifiedOnly: true,
        minPollResponses: 5,
        location: 'North America',
        ageRange: '25-55',
        gender: null,
        interests: '["digital transformation","retail","AI","business strategy","e-commerce"]',
        status: 'open',
        closesAt: new Date(now + 21 * day),
        applicationsCount: 105,
      },
      {
        creatorId: createdUsers[3].id,
        creatorUsername: createdUsers[3].username,
        creatorDisplayName: createdUsers[3].displayName,
        title: 'Global Mental Health Access & Stigma Survey',
        description: 'The World Health Organization needs your help understanding barriers to mental health care worldwide. This anonymous 10-minute survey asks about access to mental health services, personal experiences with stigma, and opinions on digital mental health interventions. All responses are strictly confidential.',
        organizationName: 'WHO Health Survey',
        sector: 'Healthcare',
        surveyType: 'health',
        estimatedMinutes: 10,
        questionsCount: 20,
        rewardPerResponse: 3.00,
        totalSlots: 1000,
        filledSlots: 756,
        totalBudget: 3000,
        minScore: 50,
        verifiedOnly: false,
        minPollResponses: 1,
        location: null,
        ageRange: '16-80',
        gender: null,
        interests: '["mental health","healthcare","public health","WHO","wellness"]',
        status: 'open',
        closesAt: new Date(now + 30 * day),
        applicationsCount: 823,
      },
      {
        creatorId: createdUsers[4].id,
        creatorUsername: createdUsers[4].username,
        creatorDisplayName: createdUsers[4].displayName,
        title: 'MBA Graduate Career Outcomes — Class of 2025',
        description: 'Harvard Business School is tracking career outcomes for MBA graduates. This 30-minute survey covers job placement, salary changes, industry shifts, entrepreneurship ventures, and satisfaction with MBA programs. Your data helps prospective students make informed decisions about business education.',
        organizationName: 'Harvard Business School',
        sector: 'Education',
        surveyType: 'academic',
        estimatedMinutes: 30,
        questionsCount: 40,
        rewardPerResponse: 10.00,
        totalSlots: 300,
        filledSlots: 201,
        totalBudget: 3000,
        minScore: 200,
        verifiedOnly: false,
        minPollResponses: 3,
        location: null,
        ageRange: '26-45',
        gender: null,
        interests: '["MBA","business education","career","higher education","graduate school"]',
        status: 'open',
        closesAt: new Date(now + 15 * day),
        applicationsCount: 267,
      },
      {
        creatorId: createdUsers[5].id,
        creatorUsername: createdUsers[5].username,
        creatorDisplayName: createdUsers[5].displayName,
        title: 'Workplace Engagement & Employee Wellbeing Index',
        description: 'Gallup\'s signature workplace survey measures employee engagement, satisfaction, burnout levels, and remote work effectiveness. This 5-minute pulse survey is conducted quarterly and results are used by thousands of organizations to improve workplace culture.',
        organizationName: 'Gallup Polls',
        sector: 'Social',
        surveyType: 'social',
        estimatedMinutes: 5,
        questionsCount: 12,
        rewardPerResponse: 2.00,
        totalSlots: 2000,
        filledSlots: 1567,
        totalBudget: 4000,
        minScore: 50,
        verifiedOnly: false,
        minPollResponses: 1,
        location: null,
        ageRange: '18-65',
        gender: null,
        interests: '["workplace","employee engagement","wellbeing","remote work","company culture"]',
        status: 'open',
        closesAt: new Date(now + 10 * day),
        applicationsCount: 1789,
      },
      {
        creatorId: createdUsers[6].id,
        creatorUsername: createdUsers[6].username,
        creatorDisplayName: createdUsers[6].displayName,
        title: 'Cloud Infrastructure Spending & Strategy — 2026',
        description: 'IDC Analytics is surveying technology leaders about cloud spending plans, multi-cloud strategies, and infrastructure priorities for 2026. This 20-minute survey covers AWS, Azure, and GCP usage patterns, migration challenges, and FinOps adoption. Results featured in our annual Cloud Market Forecast.',
        organizationName: 'IDC Analytics',
        sector: 'Technology',
        surveyType: 'market_research',
        estimatedMinutes: 20,
        questionsCount: 28,
        rewardPerResponse: 14.00,
        totalSlots: 250,
        filledSlots: 143,
        totalBudget: 3500,
        minScore: 500,
        verifiedOnly: true,
        minPollResponses: 10,
        location: null,
        ageRange: '28-55',
        gender: null,
        interests: '["cloud computing","AWS","Azure","infrastructure","DevOps"]',
        status: 'open',
        closesAt: new Date(now + 18 * day),
        applicationsCount: 198,
      },
      {
        creatorId: createdUsers[7].id,
        creatorUsername: createdUsers[7].username,
        creatorDisplayName: createdUsers[7].displayName,
        title: 'Researcher Experience with AI Writing Tools',
        description: 'Nature Research wants to understand how scientists and academics are using AI writing tools like ChatGPT and Claude in their research workflow. This 15-minute survey covers usage patterns, ethical concerns, impact on productivity, and journal submission practices. Responses inform our editorial policy on AI-assisted writing.',
        organizationName: 'Nature Research Survey',
        sector: 'Education',
        surveyType: 'academic',
        estimatedMinutes: 15,
        questionsCount: 22,
        rewardPerResponse: 8.00,
        totalSlots: 400,
        filledSlots: 278,
        totalBudget: 3200,
        minScore: 300,
        verifiedOnly: true,
        minPollResponses: 5,
        location: null,
        ageRange: '25-65',
        gender: null,
        interests: '["research","academic writing","AI tools","science","publishing"]',
        status: 'open',
        closesAt: new Date(now + 20 * day),
        applicationsCount: 356,
      },
      {
        creatorId: createdUsers[8].id,
        creatorUsername: createdUsers[8].username,
        creatorDisplayName: createdUsers[8].displayName,
        title: 'Housing Affordability & Urban Living Preferences',
        description: 'The Urban Institute is studying housing affordability challenges across major US cities. This 45-minute comprehensive survey covers current living situation, rent/mortgage burden, willingness to relocate, public transit usage, and opinions on zoning policy reforms. Your voice helps shape federal housing policy.',
        organizationName: 'Urban Institute',
        sector: 'Social',
        surveyType: 'social',
        estimatedMinutes: 45,
        questionsCount: 50,
        rewardPerResponse: 15.00,
        totalSlots: 300,
        filledSlots: 198,
        totalBudget: 4500,
        minScore: 100,
        verifiedOnly: false,
        minPollResponses: 2,
        location: 'United States',
        ageRange: '21-65',
        gender: null,
        interests: '["housing","urban living","real estate","public policy","cost of living"]',
        status: 'open',
        closesAt: new Date(now + 25 * day),
        applicationsCount: 234,
      },
      {
        creatorId: createdUsers[9].id,
        creatorUsername: createdUsers[9].username,
        creatorDisplayName: createdUsers[9].displayName,
        title: 'Product Reliability & Warranty Satisfaction — Appliances',
        description: 'Consumer Reports is gathering data on long-term reliability of major home appliances (refrigerators, washing machines, dishwashers, ovens). This 12-minute survey asks about purchase experience, repair history, warranty claims, and brand loyalty. Help millions of consumers make better purchasing decisions.',
        organizationName: 'Consumer Reports Survey',
        sector: 'Consumer',
        surveyType: 'consumer',
        estimatedMinutes: 12,
        questionsCount: 18,
        rewardPerResponse: 4.00,
        totalSlots: 800,
        filledSlots: 567,
        totalBudget: 3200,
        minScore: 100,
        verifiedOnly: false,
        minPollResponses: 2,
        location: 'United States',
        ageRange: '21-70',
        gender: null,
        interests: '["appliances","consumer products","reviews","product reliability","home"]',
        status: 'open',
        closesAt: new Date(now + 12 * day),
        applicationsCount: 623,
      },
    ];

    const created = await db.surveyListing.createMany({
      data: listings.map((l) => ({
        ...l,
        updatedAt: new Date(),
      })),
    });

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${created.count} survey listings.`,
      total: created.count,
    });
  } catch (error) {
    console.error('POST /api/survey-marketplace/seed error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to seed survey data' },
      { status: 500 }
    );
  }
}
